/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BookBelt(props) {
  const { nodes, materials } = useGLTF('models/Book2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Closed_1.geometry}
          material={materials.DarkBrown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Closed_2.geometry}
          material={materials.Beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Closed_3.geometry}
          material={materials.Gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book3_Closed_4.geometry}
          material={materials.Brown}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/Book2.glb')
