/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Book.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book2_Closed_1.geometry}
          material={materials.DarkRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book2_Closed_2.geometry}
          material={materials.Golden}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book2_Closed_3.geometry}
          material={materials.Beige}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Book.glb')
