/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DJDeck(props) {
  const { nodes, materials } = useGLTF('models/DjDeck.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DJGear_mesh.geometry}
        material={materials.DJGear_mat}
      />
    </group>
  )
}

useGLTF.preload('models/DjDeck.glb')
