/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations, useCursor } from '@react-three/drei'
import { Howl, Howler } from 'howler'
import * as THREE from 'three'

const ACTION_MAP = {
  attack: 'AnimalArmature|Attack',
  death: 'AnimalArmature|Death',
  eating: 'AnimalArmature|Eating',
  gallop: 'AnimalArmature|Gallop',
  gallopJump: 'AnimalArmature|Gallop_Jump',
  idle: 'AnimalArmature|Idle',
  idle2: 'AnimalArmature|Idle_2',
  idleHeadlow: 'AnimalArmature|Idle_2_HeadLow',
  idleHitLeft: 'AnimalArmature|Idle_HitReact_Left',
  idleHitReactRight: 'AnimalArmature|Idle_HitReact_Right',
  jumpIdle: 'AnimalArmature|Jump_ToIdle',
  walk: 'AnimalArmature|Walk',
}

export default function Husky(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/Husky.glb')
  const { actions } = useAnimations(animations, group)
  const soundRef = useRef(null)
  const [currentAction, setCurrentAction] = useState(ACTION_MAP.idle)
  const [isHovered, setIsHovered] = useState(false)

  const idleAnimations = [
    ACTION_MAP.idle,
    ACTION_MAP.idle2,
    ACTION_MAP.idleHeadlow,
  ]

  const huskyActions = [
    ACTION_MAP.attack,
    ACTION_MAP.eating,
    ACTION_MAP.gallop,
    ACTION_MAP.gallopJump,
    ACTION_MAP.jumpIdle,
    ACTION_MAP.walk,
  ]

  useEffect(() => {
    soundRef.current = new Howl({
      src: ['/sound/husky.mp3'],
      volume: 0.3,
    })
    return () => {
      if (soundRef.current) {
        soundRef.current.unload()
      }
    }
  }, [])

  useEffect(() => {
    if (!actions) return

    const action = actions[currentAction]
    if (!action) return

    Object.values(actions).forEach((a) => {
      if (a !== action) {
        a.fadeOut(0.5)
      }
    })

    if (currentAction === ACTION_MAP.idle) {
      action.reset().setLoop(THREE.LoopRepeat).fadeIn(0.5).play()
    } else {
      action.reset().setLoop(THREE.LoopOnce)
      action.clampWhenFinished = true
      action.fadeIn(0.5).play()

      const duration = action.getClip().duration * 1000
      const timeoutId = setTimeout(() => {
        if (soundRef.current) {
          soundRef.current.stop()
        }
        setCurrentAction(ACTION_MAP.idle)
      }, duration)
      return () => {
        clearTimeout(timeoutId)
      }
    }

    // Clean up
  }, [currentAction, actions])

  const handleClick = () => {
    console.log('Husky clicked ')
    if (soundRef.current) {
      soundRef.current.play()
    }

    const randomIndex = Math.floor(Math.random() * huskyActions.length)
    setCurrentAction(huskyActions[randomIndex])
  }

  useCursor(isHovered)

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={handleClick}
      onPointerOver={() => setIsHovered(true)}
      onPointerOut={() => setIsHovered(false)}
    >
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group
            name="Cube"
            position={[0, 0, 0.062]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials.Material}
              skeleton={nodes.Cube_1.skeleton}
            />
            <skinnedMesh
              name="Cube_2"
              geometry={nodes.Cube_2.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Cube_2.skeleton}
            />
            <skinnedMesh
              name="Cube_3"
              geometry={nodes.Cube_3.geometry}
              material={materials['Material.006']}
              skeleton={nodes.Cube_3.skeleton}
            />
            <skinnedMesh
              name="Cube_4"
              geometry={nodes.Cube_4.geometry}
              material={materials['Material.003']}
              skeleton={nodes.Cube_4.skeleton}
            />
            <skinnedMesh
              name="Cube_5"
              geometry={nodes.Cube_5.geometry}
              material={materials['Material.002']}
              skeleton={nodes.Cube_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/Husky.glb')
