/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Lamp.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Light_Stand1_1.geometry}
          material={materials.LightMetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Light_Stand1_2.geometry}
          material={materials.White}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Lamp.glb')
