/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { Outlines, useCursor, useGLTF } from '@react-three/drei'
import { useWindowStore } from '../ui/windowStore'

export default function Laptop({ handleLaptopClick, ...props }) {
  const { nodes, materials } = useGLTF('models/Laptop.glb')
  const [isLaptopHovered, setIsLaptopHovered] = useState(false)

  useCursor(isLaptopHovered)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.laptop.geometry}
        material={materials.laptop_albedo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        onPointerOver={() => setIsLaptopHovered(true)}
        onPointerOut={() => setIsLaptopHovered(false)}
        onClick={(e) => {
          e.stopPropagation()
          console.log('Mesh clicked calling laptop click')
          handleLaptopClick()
        }}
      >
        {isLaptopHovered && <Outlines thickness={2} color="#d1ccad" />}
      </mesh>
    </group>
  )
}

useGLTF.preload('models/Laptop.glb')
