/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LCouch(props) {
  const { nodes, materials } = useGLTF('models/LCouch.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_L_1.geometry}
          material={materials.Couch_BeigeDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_L_2.geometry}
          material={materials.Couch_Beige}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/LCouch.glb')
