/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OpenBook1(props) {
  const { nodes, materials } = useGLTF('models/openBook1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book1_Open_1.geometry}
          material={materials.Beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Book1_Open_2.geometry}
          material={materials.DarkRed}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/openBook1.glb')
