/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Painting(props) {
  const { nodes, materials } = useGLTF('models/Painting.glb')
  const paintingRef = useRef()
  const handleClick = () => {
    console.log('suzanne clicked')
  }
  const [hovered, setHovered] = useState(false)

  return (
    <group
      {...props}
      dispose={null}
      ref={paintingRef}
      onClick={(e) => {
        e.stopPropagation()
        handleClick()
      }}
      onPointerOver={(e) => {
        e.stopPropagation()
        setHovered(true)
        document.body.style.cursor = 'pointer'
      }}
      onPointerOut={() => {
        setHovered(false)
        document.body.style.cursor = 'default'
      }}
      scale={hovered ? 105 : 100}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Painting.geometry}
        material={materials.Material}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('models/Painting.glb')
