/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Record(props) {
  const { nodes, materials } = useGLTF('models/Record.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl001.geometry}
        material={materials['07___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox003.geometry}
        material={materials['01___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox004.geometry}
        material={materials['01___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox010.geometry}
        material={materials['04___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl008.geometry}
        material={materials['04___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox013.geometry}
        material={materials['07___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox014.geometry}
        material={materials['07___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1.geometry}
        material={materials['04___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_1.geometry}
        material={materials['05___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_2.geometry}
        material={materials['06___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_3.geometry}
        material={materials['09___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_4.geometry}
        material={materials['01___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_5.geometry}
        material={materials['02___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferCyl009_1_6.geometry}
        material={materials['07___Default']}
      />
    </group>
  )
}

useGLTF.preload('models/Record.glb')
