/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Vines(props) {
  const { nodes, materials } = useGLTF('models/Vines.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ivy.geometry}
        material={materials.None}
      />
    </group>
  )
}

useGLTF.preload('models/Vines.glb')
