/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WallCorner(props) {
  const { nodes, materials } = useGLTF('models/WallCorner.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['wall-corner'].geometry}
        material={materials.colormap}
      />
    </group>
  )
}

useGLTF.preload('models/WallCorner.glb')
