/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { Outlines, useCursor, useGLTF } from '@react-three/drei'
import { Bloom } from '@react-three/postprocessing'

export default function CozyRoom({
  onBookcaseClick,
  onCreditsClick,
  onDecksClick,
  onFireClick,
  onGuitarClick,
  onLampClick,
  isLampOn,
  ...props
}) {
  const { nodes, materials } = useGLTF('models/cozyroom.glb')
  const bookRef = useRef()
  const toReadRef = useRef()
  const readingRef = useRef()

  const [isBookcaseHovered, setIsBookcaseHovered] = useState(false)
  const [isToReadHovered, setIsToReadHovered] = useState(false)
  const [isReadingHovered, setIsReadingHovered] = useState(false)
  const [isCreditsHovered, setIsCreditsHovered] = useState(false)
  const [isGuitarHovered, setIsGuitarHovered] = useState(false)
  const [isLampHovered, setIsLampHovered] = useState(false)
  const [isFireHovered, setIsFireHovered] = useState(false)
  const [isDeckHovered, setIsDeckHovered] = useState(false)
  const [isHeadphonesHovered, setIsHeadphonesHovered] = useState(false)
  const [isOrchidHovered, setIsOrchidHovered] = useState(false)
  const [isPlantHovered, setIsPlantHovered] = useState(false)

  useCursor(
    isBookcaseHovered ||
      isToReadHovered ||
      isReadingHovered ||
      isCreditsHovered ||
      isGuitarHovered ||
      isLampHovered ||
      isFireHovered ||
      isDeckHovered ||
      isOrchidHovered ||
      isPlantHovered ||
      isHeadphonesHovered,
  )

  return (
    <>
      <group {...props} dispose={null}>
        {/* walls */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CornerWall.geometry}
          material={materials['colormap.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wall.geometry}
          material={materials['colormap.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall1.geometry}
          material={materials['colormap.003']}
        />

        {/* Floor */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plank1.geometry}
          material={materials['restaurant.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plank2.geometry}
          material={materials['restaurant.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plank3.geometry}
          material={materials['restaurant.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plank4.geometry}
          material={materials['restaurant.001']}
        />

        {/* Table */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Table.geometry}
          material={materials['wood.001']}
        />

        {/* Painting for Credits */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Painting.geometry}
          material={materials['Material.007']}
          onPointerOver={() => setIsCreditsHovered(true)}
          onPointerOut={() => setIsCreditsHovered(false)}
          onClick={onCreditsClick}
        >
          {isCreditsHovered && <Outlines thickness={2} color="#d1ccad" />}
        </mesh>

        {/* DJ Decks */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DJDeck.geometry}
          material={materials['DJGear_mat.001']}
          onPointerOver={() => setIsDeckHovered(true)}
          onPointerOut={() => setIsDeckHovered(false)}
          onClick={onDecksClick}
        />

        {/* Windows */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_mesh.geometry}
          material={materials['mat16.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Window_mesh_1.geometry}
          material={materials['mat22.003']}
        />

        {/* Fireplace */}
        <group
          onPointerOver={() => setIsFireHovered(true)}
          onPointerOut={() => setIsFireHovered(false)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh.geometry}
            material={materials['lambert5SG.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_1.geometry}
            material={materials['lambert6SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_2.geometry}
            material={materials['lambert4SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_3.geometry}
            material={materials['lambert3SG.002']}
            onClick={onFireClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_4.geometry}
            material={materials['lambert9SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_5.geometry}
            material={materials['lambert8SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.fireplace_mesh_6.geometry}
            material={materials['lambert7SG.002']}
          />
        </group>

        {/* Couch */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_L_mesh.geometry}
          material={materials['Couch_BeigeDark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Couch_L_mesh_1.geometry}
          material={materials['Couch_Beige.001']}
        />

        {/* Lamp */}
        <group
          onPointerOver={() => setIsLampHovered(true)}
          onPointerOut={() => setIsLampHovered(false)}
          onClick={onLampClick}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_mesh.geometry}
            material={materials['LightMetal.001']}
          />
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lamp_mesh_1.geometry}
            material={materials['White.001']}
          /> */}
          <mesh castShadow receiveShadow geometry={nodes.Lamp_mesh_1.geometry}>
            <meshStandardMaterial
              color="white"
              emissive="orange"
              emissiveIntensity={isLampOn ? 4 : 0} // Push it out of range when on
            />
          </mesh>
        </group>

        {/* Plant */}
        <group
          onPointerOver={() => setIsPlantHovered(true)}
          onPointerOut={() => setIsPlantHovered(false)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plant_mesh.geometry}
            material={materials['Black.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plant_mesh_1.geometry}
            material={materials['Brown.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plant_mesh_2.geometry}
            material={materials['Plant_Green.001']}
          />
        </group>

        {/** Read Bookcase */}
        <group
          onPointerOver={() => setIsBookcaseHovered(true)}
          onPointerOut={() => setIsBookcaseHovered(false)}
          onClick={() => onBookcaseClick('read')}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh.geometry}
            material={materials['Wood1.001']}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_1.geometry}
            material={materials['Wood2.001']}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_2.geometry}
            material={materials['DarkWood.001']}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_3.geometry}
            material={materials['Cover1.001']}
          >
            {' '}
            {isBookcaseHovered && <Outlines thickness={1.5} color="#d1ccad" />}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_4.geometry}
            material={materials['Pages.001']}
          >
            {isBookcaseHovered && <Outlines thickness={1.5} color="#d1ccad" />}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_5.geometry}
            material={materials['Cover6.001']}
          >
            {isBookcaseHovered && <Outlines thickness={1.5} color="#d1ccad" />}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_6.geometry}
            material={materials['Cover2.001']}
          >
            {isBookcaseHovered && <Outlines thickness={1.5} color="#d1ccad" />}
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_7.geometry}
            material={materials['Cover3.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_8.geometry}
            material={materials['Cover4.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_9.geometry}
            material={materials['Cover5.001']}
          />

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bookcase_mesh_10.geometry}
            material={materials['Metal.001']}
          />
        </group>

        {/* Guitar */}
        <group
          onPointerOver={() => setIsGuitarHovered(true)}
          onPointerOut={() => setIsGuitarHovered(false)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh.geometry}
            material={materials['_LightGray_.001']}
            onClick={onGuitarClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh_1.geometry}
            material={materials['_Tan_.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh_2.geometry}
            material={materials['_SaddleBrown_.001']}
            onClick={onGuitarClick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh_3.geometry}
            material={materials['_Gold_.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh_4.geometry}
            material={materials['scan_4.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.guitar_mesh_5.geometry}
            material={materials['_Gray_.001']}
          />
        </group>

        {/* Orchid */}
        <group
          onPointerOver={() => setIsOrchidHovered(true)}
          onPointerOut={() => setIsOrchidHovered(false)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh.geometry}
            material={materials['lambert23SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh_1.geometry}
            material={materials['lambert20SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh_2.geometry}
            material={materials['lambert21SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh_3.geometry}
            material={materials['lambert22SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh_4.geometry}
            material={materials['lambert25SG.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Orchid_mesh_5.geometry}
            material={materials['lambert24SG.001']}
          />
        </group>

        {/* Headphones */}
        <group
          onPointerOver={() => setIsHeadphonesHovered(true)}
          onPointerOut={() => setIsHeadphonesHovered(false)}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.headphones_mesh.geometry}
            material={materials['lambert7SG.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.headphones_mesh_1.geometry}
            material={materials['lambert5SG.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.headphones_mesh_2.geometry}
            material={materials['lambert3SG.003']}
          />
        </group>

        {/** TO READ Models */}
        <mesh
          castShadow
          receiveShadow
          onPointerOver={() => setIsToReadHovered(true)}
          onPointerOut={() => setIsToReadHovered(false)}
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.bottom_book_mesh.geometry}
          material={materials['DarkRed.003']}
        >
          {isToReadHovered && <Outlines thickness={2} color="#d1ccad" />}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.bottom_book_mesh_1.geometry}
          material={materials['Golden.001']}
        />
        <mesh
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.bottom_book_mesh_2.geometry}
          material={materials['Beige.004']}
        />
        <mesh
          onPointerOver={() => setIsToReadHovered(true)}
          onPointerOut={() => setIsToReadHovered(false)}
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.top_book_mesh.geometry}
          material={materials['DarkRed.003']}
        >
          {isToReadHovered && <Outlines thickness={2} color="#d1ccad" />}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.top_book_mesh_1.geometry}
          material={materials['Golden.001']}
        />
        <mesh
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('toRead')}
          geometry={nodes.top_book_mesh_2.geometry}
          material={materials['Beige.004']}
        />

        {/** READING */}
        <mesh
          castShadow
          receiveShadow
          onPointerOver={() => {
            setIsReadingHovered(true)
          }}
          onPointerOut={() => setIsReadingHovered(false)}
          onClick={() => onBookcaseClick('reading')}
          geometry={nodes.Book1_Open001.geometry}
          material={materials['Beige.006']}
        />
        <mesh
          ref={readingRef}
          onPointerOver={() => {
            setIsReadingHovered(true)
          }}
          onPointerOut={() => setIsReadingHovered(false)}
          castShadow
          receiveShadow
          onClick={() => onBookcaseClick('reading')}
          geometry={nodes.Book1_Open001_1.geometry}
          material={materials['DarkRed.005']}
        >
          {isReadingHovered && <Outlines thickness={2} color="#d1ccad" />}
        </mesh>
      </group>
    </>
  )
}

useGLTF.preload('models/cozyroom.glb')
